### ISSUE TITLE
"Watch task over kubernetes Container resources terminated unexpectedly. Check to ensure dcpd process is running."

### ISSUE THREAD

**Issue by atrauzzi** [microsoft/aspire#4582]
Running with podman on Fedora 40:

```csharp
var minio = builder
    .AddContainer("minio", "minio/minio")
    .WithEnvironment("MINIO_ROOT_USER", "blah")
    .WithEnvironment("MINIO_ROOT_PASSWORD", "blah")
    .WithVolume("storage", "/minio")
    .WithArgs(["server", "--console-address", "0.0.0.0:8075", "--address", "0.0.0.0:8078", "--compat", "/minio"])
    .WithHttpsEndpoint(8075, 8075)
    .WithHttpsEndpoint(8078, 8078)
;
```

I end up getting this exception:

```
crit: Aspire.Hosting.Dcp.ApplicationExecutor[0]
      Watch task over kubernetes Service resources terminated unexpectedly. Check to ensure dcpd process is running.
      System.InvalidOperationException: Sequence contains more than one matching element
         at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
         at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
         at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
         at Aspire.Hosting.ApplicationModel.EndpointReference.GetEndpointAnnotation() in /_/src/Aspire.Hosting/ApplicationModel/EndpointReference.cs:line 111
         at Aspire.Hosting.ApplicationModel.EndpointReference.get_EndpointAnnotation() in /_/src/Aspire.Hosting/ApplicationModel/EndpointReference.cs:line 18
         at Aspire.Hosting.Dcp.ApplicationExecutor.GetUrls(CustomResource resource) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 644
         at Aspire.Hosting.Dcp.ApplicationExecutor.ToSnapshot(Container container, CustomResourceSnapshot previous) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 527
         at Aspire.Hosting.Dcp.ApplicationExecutor.<>c__DisplayClass37_0.<TryRefreshResource>b__0(CustomResourceSnapshot s) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 511
         at Aspire.Hosting.ApplicationModel.ResourceNotificationService.PublishUpdateAsync(IResource resource, String resourceId, Func`2 stateFactory) in /_/src/Aspire.Hosting/ApplicationModel/ResourceNotificationService.cs:line 75
         at Aspire.Hosting.Dcp.ApplicationExecutor.TryRefreshResource(String resourceKind, String resourceName) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 507
         at Aspire.Hosting.Dcp.ApplicationExecutor.ProcessServiceChange(WatchEventType watchEventType, Service service) in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 487
         at Aspire.Hosting.Dcp.ApplicationExecutor.<>c__DisplayClass32_1`1.<<WatchResourceChanges>b__10>d.MoveNext() in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 291
      --- End of stack trace from previous location ---
         at Aspire.Hosting.Dcp.ApplicationExecutor.<>c__DisplayClass32_1`1.<<WatchResourceChanges>b__10>d.MoveNext() in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 285
      --- End of stack trace from previous location ---
         at Polly.ResiliencePipeline.<>c.<<ExecuteAsync>b__3_0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Polly.Outcome`1.GetResultOrRethrow()
         at Polly.ResiliencePipeline.ExecuteAsync(Func`2 callback, CancellationToken cancellationToken)
         at Aspire.Hosting.Dcp.ApplicationExecutor.<>c__DisplayClass32_0.<<WatchResourceChanges>g__WatchKubernetesResource|3>d`1.MoveNext() in /_/src/Aspire.Hosting/Dcp/ApplicationExecutor.cs:line 281
```
Looks like this happens when I don't give the port mappings names?  Might be useful to trap that and return an explicit message to be more informative [here-ish](https://github.com/dotnet/aspire/blob/main/src/Aspire.Hosting/ApplicationModel/EndpointReference.cs#L111)?

**Comment by mitchdenny** [comment]
@atrauzzi thanks for reporting this. Smells like either a bug or a usability issue (at the least). Will add it to the backlog for now. Just want to confirm that if you name the endpoints it works as expected?

**Comment by davidfowl** [comment]
This is because the endpoint name is ambiguous.

**Comment by mitchdenny** [comment]
Yeah it's expected. The bug is that the error should be more helpful

**Comment by taniasimpson** [comment]
Hi! I am experiencing an error for: ` Watch task over Kubernetes Service resources terminated unexpectedly. Check to ensure dcpd process is running.`

However mine is different after the original "Check to ensure dcpd process is running" issue mentioned (if I need to open a new bug I will, just let me know) but I have attached it. 
[Aspire.Hosting.Dcp.txt](https://github.com/user-attachments/files/16431606/Aspire.Hosting.Dcp.txt)

I can start the application multiple times in a row get the error and then randomly no error.

I am not connected to VPN. No code changes during this time. The containers seem to start in Docker as they should. But the dashboard is not in sync with the resources while I am getting the error. What can I do to eliminate the error and get consistent clean starts? 

My Host Program file: 

```var builder = DistributedApplication.CreateBuilder(args);

//Create resources
var cache = builder.AddRedis("cache");

var sqlServer = builder.AddSqlServer("sqlserver")
    .PublishAsAzureSqlDatabase()
    .AddDatabase("sqldb");

//Add projects and dependencies
builder.AddProject<Projects.aspire_test_app_Api>("aspire-test-app-api")
    .WithReference(cache)
    .WithReference(sqlServer);

builder.AddProject<Projects.aspire_test_app_Services>("aspire-test-app-services")
    .WithReference(cache)
    .WithReference(sqlServer);

builder.AddProject<Projects.aspire_test_app_DatabaseMigrationService>("aspire-test-app-databasemigrationservice")
    .WithReference(sqlServer);

builder.Build().Run();

**Comment by joperezr** [comment]
As part of triage cleanup ahead of the 13.3 release, this issue is being moved to the Backlog milestone. If you believe it should remain in 13.3, feel free to re-add to the milestone and leave a comment here why it should not be punted.

**Comment by adamint** [comment]
@atrauzzi are you still running into this issue?

**Comment by Lakelimbo** [comment]
I'm running into a similar issue, although with a slightly different backtrace (coming from `Polly.Timeout.TimeoutRejectedException` and `System.Threading.Tasks.TaskCanceledException`), which started to happen today when upgrading the Aspire SDK from 13.3.5 to 13.4.2.
The only way I found to avoid this is by downgrading the updated packages until this issue is resolved.

**Comment by davidfowl** [comment]
@Lakelimbo similar or the same? Is it this?

**Comment by Lakelimbo** [comment]
@davidfowl Looks like it's more related to this #18050 specifically, even though part of the error is the same. But considering this issue here is almost 2 years old, I think it's not the same.
I'll continue discussion on that thread from then on.

**Comment by karolz-ms** [comment]
Let's continue discussion using the fresh issue like @Lakelimbo  said
